// <auto-generated />
using System;
using FortyNineRideChallenge;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace sdgreacttemplate.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20191004174320_AddedChallengeAttemptsModel")]
    partial class AddedChallengeAttemptsModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("FortyNineRideChallenge.Models.ChallengeAttempts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("RidesCompleted");

                    b.Property<DateTime>("TimeEnded");

                    b.Property<DateTime>("TimeStarted");

                    b.HasKey("Id");

                    b.ToTable("ChallengeAttempt");
                });

            modelBuilder.Entity("FortyNineRideChallenge.Models.DisneyWorldParks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ParkName");

                    b.HasKey("Id");

                    b.ToTable("DisneyWorldPark");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            ParkName = "Magic Kingdom"
                        },
                        new
                        {
                            Id = -2,
                            ParkName = "Animal Kingdom"
                        },
                        new
                        {
                            Id = -3,
                            ParkName = "Hollywood Studios"
                        },
                        new
                        {
                            Id = -4,
                            ParkName = "Epcot"
                        });
                });

            modelBuilder.Entity("FortyNineRideChallenge.Models.DisneyWorldRides", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Complete");

                    b.Property<int>("DisneyWorldParkId");

                    b.Property<int?>("DisneyWorldParksId");

                    b.Property<string>("RideName");

                    b.HasKey("Id");

                    b.HasIndex("DisneyWorldParksId");

                    b.ToTable("DisneyWorldRide");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "Main Street Vehicles"
                        },
                        new
                        {
                            Id = -2,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "Walt Disney World Railroad"
                        },
                        new
                        {
                            Id = -3,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "Jungle Cruise"
                        },
                        new
                        {
                            Id = -4,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "Pirates of the Caribbean"
                        },
                        new
                        {
                            Id = -5,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "Magic Carpets of Aladdin"
                        },
                        new
                        {
                            Id = -6,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "Splash Mountain"
                        },
                        new
                        {
                            Id = -7,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "Big Thunder Mountain"
                        },
                        new
                        {
                            Id = -8,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "Rafts to Tom Sawyer Island"
                        },
                        new
                        {
                            Id = -9,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "Liberty Belle Riverboat"
                        },
                        new
                        {
                            Id = -10,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "Haunted Mansion"
                        },
                        new
                        {
                            Id = -11,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "It’s a Small World"
                        },
                        new
                        {
                            Id = -12,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "Peter Pan’s Flight"
                        },
                        new
                        {
                            Id = -13,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "Prince Charming Regal Carousel"
                        },
                        new
                        {
                            Id = -14,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "Many Adventures of Winnie the Pooh"
                        },
                        new
                        {
                            Id = -15,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "Under the Sea — Journey of the Little Mermaid"
                        },
                        new
                        {
                            Id = -16,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "Seven Dwarfs Mine Train"
                        },
                        new
                        {
                            Id = -17,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "Mad Tea Party"
                        },
                        new
                        {
                            Id = -18,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "Dumbo the Flying Elephant"
                        },
                        new
                        {
                            Id = -19,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "Barnstormer"
                        },
                        new
                        {
                            Id = -20,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "Tomorrowland Speedway"
                        },
                        new
                        {
                            Id = -21,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "Tomorrowland Transit Authority PeopleMover"
                        },
                        new
                        {
                            Id = -22,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "Space Mountain"
                        },
                        new
                        {
                            Id = -23,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "Buzz Lightyear Space Ranger Spin"
                        },
                        new
                        {
                            Id = -24,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "AstroOrbiter"
                        },
                        new
                        {
                            Id = -25,
                            Complete = false,
                            DisneyWorldParkId = -1,
                            RideName = "Carousel of Progress"
                        },
                        new
                        {
                            Id = -26,
                            Complete = false,
                            DisneyWorldParkId = -2,
                            RideName = "Kilimanjaro Safari"
                        },
                        new
                        {
                            Id = -27,
                            Complete = false,
                            DisneyWorldParkId = -2,
                            RideName = "Wildlife Express"
                        },
                        new
                        {
                            Id = -28,
                            Complete = false,
                            DisneyWorldParkId = -2,
                            RideName = "Kali River Rapids"
                        },
                        new
                        {
                            Id = -29,
                            Complete = false,
                            DisneyWorldParkId = -2,
                            RideName = "Expedition Everest"
                        },
                        new
                        {
                            Id = -30,
                            Complete = false,
                            DisneyWorldParkId = -2,
                            RideName = "Dinosaur"
                        },
                        new
                        {
                            Id = -31,
                            Complete = false,
                            DisneyWorldParkId = -2,
                            RideName = "Primeval Whirl"
                        },
                        new
                        {
                            Id = -32,
                            Complete = false,
                            DisneyWorldParkId = -2,
                            RideName = "TriceraTop Spin"
                        },
                        new
                        {
                            Id = -33,
                            Complete = false,
                            DisneyWorldParkId = -2,
                            RideName = "Flight of Passage"
                        },
                        new
                        {
                            Id = -34,
                            Complete = false,
                            DisneyWorldParkId = -2,
                            RideName = "Na’vi River Journey"
                        },
                        new
                        {
                            Id = -35,
                            Complete = false,
                            DisneyWorldParkId = -3,
                            RideName = "Toy Story Midway Mania"
                        },
                        new
                        {
                            Id = -36,
                            Complete = false,
                            DisneyWorldParkId = -3,
                            RideName = "Star Tours"
                        },
                        new
                        {
                            Id = -37,
                            Complete = false,
                            DisneyWorldParkId = -3,
                            RideName = "Rock ‘n’ Roller Coaster"
                        },
                        new
                        {
                            Id = -38,
                            Complete = false,
                            DisneyWorldParkId = -3,
                            RideName = "Twilight Zone Tower of Terror"
                        },
                        new
                        {
                            Id = -39,
                            Complete = false,
                            DisneyWorldParkId = -3,
                            RideName = "Slinky Dog Dash"
                        },
                        new
                        {
                            Id = -40,
                            Complete = false,
                            DisneyWorldParkId = -3,
                            RideName = "Alien Swirling Saucers"
                        },
                        new
                        {
                            Id = -41,
                            Complete = false,
                            DisneyWorldParkId = -3,
                            RideName = "Millennium Falcon Smugglers Run"
                        },
                        new
                        {
                            Id = -42,
                            Complete = false,
                            DisneyWorldParkId = -4,
                            RideName = "Spaceship Earth"
                        },
                        new
                        {
                            Id = -43,
                            Complete = false,
                            DisneyWorldParkId = -4,
                            RideName = "Mission: SPACE"
                        },
                        new
                        {
                            Id = -44,
                            Complete = false,
                            DisneyWorldParkId = -4,
                            RideName = "Test Track"
                        },
                        new
                        {
                            Id = -45,
                            Complete = false,
                            DisneyWorldParkId = -4,
                            RideName = "Journey Into Imagination"
                        },
                        new
                        {
                            Id = -46,
                            Complete = false,
                            DisneyWorldParkId = -4,
                            RideName = "Soarin’"
                        },
                        new
                        {
                            Id = -47,
                            Complete = false,
                            DisneyWorldParkId = -4,
                            RideName = "Living with the Land"
                        },
                        new
                        {
                            Id = -48,
                            Complete = false,
                            DisneyWorldParkId = -4,
                            RideName = "The Seas with Nemo and Friends"
                        },
                        new
                        {
                            Id = -49,
                            Complete = false,
                            DisneyWorldParkId = -4,
                            RideName = "Frozen Ever After"
                        });
                });

            modelBuilder.Entity("FortyNineRideChallenge.Models.DisneyWorldRides", b =>
                {
                    b.HasOne("FortyNineRideChallenge.Models.DisneyWorldParks", "DisneyWorldParks")
                        .WithMany("DisneyWorldRide")
                        .HasForeignKey("DisneyWorldParksId");
                });
#pragma warning restore 612, 618
        }
    }
}
